// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package pkg

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MismatchContentDetails) DeepCopyInto(out *MismatchContentDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MismatchContentDetails.
func (in *MismatchContentDetails) DeepCopy() *MismatchContentDetails {
	if in == nil {
		return nil
	}
	out := new(MismatchContentDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResponseDetails) DeepCopyInto(out *ResponseDetails) {
	*out = *in
	if in.IdsMissingFromElasticsearch != nil {
		in, out := &in.IdsMissingFromElasticsearch, &out.IdsMissingFromElasticsearch
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IdsOnlyInElasticsearch != nil {
		in, out := &in.IdsOnlyInElasticsearch, &out.IdsOnlyInElasticsearch
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IdsWithMismatchContent != nil {
		in, out := &in.IdsWithMismatchContent, &out.IdsWithMismatchContent
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MismatchContentDetails != nil {
		in, out := &in.MismatchContentDetails, &out.MismatchContentDetails
		*out = make([]MismatchContentDetails, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResponseDetails.
func (in *ResponseDetails) DeepCopy() *ResponseDetails {
	if in == nil {
		return nil
	}
	out := new(ResponseDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationResponse) DeepCopyInto(out *ValidationResponse) {
	*out = *in
	in.Details.DeepCopyInto(&out.Details)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationResponse.
func (in *ValidationResponse) DeepCopy() *ValidationResponse {
	if in == nil {
		return nil
	}
	out := new(ValidationResponse)
	in.DeepCopyInto(out)
	return out
}
