//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package pkg

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContentDetails) DeepCopyInto(out *ContentDetails) {
	*out = *in
	if in.IdsWithMismatchContent != nil {
		in, out := &in.IdsWithMismatchContent, &out.IdsWithMismatchContent
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MismatchContentDetails != nil {
		in, out := &in.MismatchContentDetails, &out.MismatchContentDetails
		*out = make(MismatchedRecords, len(*in))
		for key, val := range *in {
			var outVal *ContentDiff
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(ContentDiff)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContentDetails.
func (in *ContentDetails) DeepCopy() *ContentDetails {
	if in == nil {
		return nil
	}
	out := new(ContentDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContentDiff) DeepCopyInto(out *ContentDiff) {
	*out = *in
	if in.Diffs != nil {
		in, out := &in.Diffs, &out.Diffs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContentDiff.
func (in *ContentDiff) DeepCopy() *ContentDiff {
	if in == nil {
		return nil
	}
	out := new(ContentDiff)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CountDetails) DeepCopyInto(out *CountDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CountDetails.
func (in *CountDetails) DeepCopy() *CountDetails {
	if in == nil {
		return nil
	}
	out := new(CountDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatasourceDBConnection) DeepCopyInto(out *DatasourceDBConnection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatasourceDBConnection.
func (in *DatasourceDBConnection) DeepCopy() *DatasourceDBConnection {
	if in == nil {
		return nil
	}
	out := new(DatasourceDBConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdsDetails) DeepCopyInto(out *IdsDetails) {
	*out = *in
	if in.IdsMissingFromElasticsearch != nil {
		in, out := &in.IdsMissingFromElasticsearch, &out.IdsMissingFromElasticsearch
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IdsOnlyInElasticsearch != nil {
		in, out := &in.IdsOnlyInElasticsearch, &out.IdsOnlyInElasticsearch
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdsDetails.
func (in *IdsDetails) DeepCopy() *IdsDetails {
	if in == nil {
		return nil
	}
	out := new(IdsDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in MismatchedRecords) DeepCopyInto(out *MismatchedRecords) {
	{
		in := &in
		*out = make(MismatchedRecords, len(*in))
		for key, val := range *in {
			var outVal *ContentDiff
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(ContentDiff)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MismatchedRecords.
func (in MismatchedRecords) DeepCopy() MismatchedRecords {
	if in == nil {
		return nil
	}
	out := new(MismatchedRecords)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResponseDetails) DeepCopyInto(out *ResponseDetails) {
	*out = *in
	out.Counts = in.Counts
	in.IDs.DeepCopyInto(&out.IDs)
	in.Content.DeepCopyInto(&out.Content)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResponseDetails.
func (in *ResponseDetails) DeepCopy() *ResponseDetails {
	if in == nil {
		return nil
	}
	out := new(ResponseDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidationResponse) DeepCopyInto(out *ValidationResponse) {
	*out = *in
	in.Details.DeepCopyInto(&out.Details)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidationResponse.
func (in *ValidationResponse) DeepCopy() *ValidationResponse {
	if in == nil {
		return nil
	}
	out := new(ValidationResponse)
	in.DeepCopyInto(out)
	return out
}
